### PR TITLE
New Odin API + better SARIF ouput

### PR DESCRIPTION
**Pull request by nikololiahim**
This PR:
- changes Polystat to accomodate for changes in the Odin Interop https://github.com/polystat/odin/pull/43
- changes AsSarif.java to produce an output that conforms to the SARIF spec (more details in #49)

Odin changes are not published yet, so CI should not pass.
This PR includes changes made in #51.

Now, the EO code in `test.eo`:
```
[] > test
  [] > base
    [self v] > n
      v > @
    [self v] > m
      self.n self v > @
  [] > derived
    base > @
    [self v] > n
      self.m self v > @
```
produces the following output with the `--sarif` option (prettified):
```json
{
  "version": "2.1.0",
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Polystat",
          "informationUri": "https://www.polystat.org/",
          "semanticVersion": "1.0-SNAPSHOT"
        }
      },
      "results": [
        {
          "ruleId": "AnFaR/Division by zero",
          "level": "none",
          "kind": "pass",
          "message": {
            "text": "No errors were found."
          }
        },
        {
          "ruleId": "AnOdin/Mutual Recursion",
          "level": "error",
          "kind": "fail",
          "message": {
            "text": "test.derived: test.derived.m (was last redefined in \"test.base\") -> test.derived.n -> test.derived.m (was last redefined in \"test.base\")"
          }
        }
      ],
      "invocations": [
        {
          "toolExecutionNotifications": [
            {
              "message": {
                "text": "Analyzer \"AnFaR/Division by zero\" completed successfully. No errors were found"
              },
              "associatedRule": {
                "id": "AnFaR/Division by zero"
              }
            }
          ],
          "executionSuccessful": true
        },
        {
          "toolExecutionNotifications": [
            {
              "message": {
                "text": "Analyzer \"AnOdin/Mutual Recursion\" completed successfully. Some errors were found."
              },
              "associatedRule": {
                "id": "AnOdin/Mutual Recursion"
              }
            }
          ],
          "executionSuccessful": true
        },
        {
          "toolExecutionNotifications": [
            {
              "exception": {
                "kind": "java.lang.Exception",
                "message": "SMT failed to parse the generated program with error: assertion failed"
              },
              "level": "error",
              "message": {
                "text": "SMT failed to parse the generated program with error: assertion failed"
              },
              "associatedRule": {
                "id": "AnOdin/Unjustified Assumption"
              }
            }
          ],
          "executionSuccessful": false
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by nikololiahim** [comment]
@yegor256 @fizruk what do you think?

**Comment by nikololiahim** [comment]
I'll extend the test suite when I figure out how to use JUnit.

**Comment by fizruk** [comment]
Looks good to me! First step towards a better SARIF support 👍

**Comment by yegor256** [comment]
@nikololiahim I like it!

**Comment by nikololiahim** [comment]
I have made sure that tests + qulice checks pass locally. One thing that is left is to release a suitable version of Odin. 
If the test coverage is not sufficient (it most likely is), I will add more tests to the `AsSariftTests` suite.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
