### PR TITLE
Integrating Mutual Recursion Analyzer

### PR DESCRIPTION
**Pull request by nikololiahim**
Scala source code from [here](https://github.com/Sitiritis/eo-static-analyzer/tree/demo) was adopted as follows:
- A `pom.xml` file was created for each of the submodules.
- Scala code was successfully compiled and tested through Maven (without `-Pqulice`, though)
- Existing code in Polystat was moved to a separate Maven submodule called `polystat` (temporary name).
- The Scala Maven project was added to Polystat under the name `mutual_recursion_analyzer` (temporary name).
- The root `pom.xml` artifact is now called `polystat-parent` (temporary name).

### CODE REVIEW

**Comment by nikololiahim** [comment]
@yegor256 can you have a look? The problem with CI so far is that there are no LICENSE.txt files in the modules. What should the license be?

**Comment by yegor256** [comment]
@nikololiahim I feel that we are doing it wrong. Having two programming languages in one repository is not a good idea. How about you create your own repository, put your code there, configure CI/CD over there, and deploy your module to Maven Central. Then, let Polystat just use it, as a dependency. What do you think?

**Comment by nikololiahim** [comment]
@yegor256 on the other hand, having all code in one repository significantly simplifies integration testing. 

Also, Scala and Java aren't that different, since they are compiled to exactly the same class files. The FindBugs was just as OK with Scala class files as it was with Java class files. The main reason it complains is that Scala case classes implement `Serializable` under the hood but do not generate the `SerialUID` constant. Adding `SerialUID` to Scala case classes is doable, but very tedious.

**Comment by yegor256** [comment]
@nikololiahim there are many discussions about that, while I believe in small repos, check this out: https://www.yegor256.com/2018/09/05/monolithic-repositories.html You will see how convenient it will be for you to maintain your own repo avoiding conflicts with this one

**Pull request closed without merging**
